CONTIKI_PROJECT = hello-world
all: $(CONTIKI_PROJECT)

UIP_CONF_IPV6=1

all:  $(CONTIKI_PROJECT) $(CONTIKI_PROJECT).size $(CONTIKI_PROJECT).bin $(CONTIKI_PROJECT).upload


CONTIKI = ../..
include $(CONTIKI)/Makefile.include
