CONTIKI_PROJECT = hello-world

all: $(CONTIKI_PROJECT) $(CONTIKI_PROJECT).size $(CONTIKI_PROJECT).bin $(CONTIKI_PROJECT).upload
	@echo " "
	@echo "** Build done **************************************"
	@echo " "


CONTIKI = ../../..
include $(CONTIKI)/Makefile.include
